version: "3.8"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    depends_on:
      - postgres_db
    networks:
      - task_network
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_DATABASE: mentory
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./backend:/var/www/html

  remix:
    build:
      context: ./frontend
    container_name: remix_app
    ports:
      - "3100:3100"
    volumes:
      - ./frontend:/app:cached
    networks:
      - task_network

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mentory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - task_network
networks:
  task_network:
    driver: bridge

volumes:
  postgres_data:
